export const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  COMERCIAL: 'COMERCIAL',
};

export const ORDER_STATUS = {
  PENDIENTE: 'PENDIENTE',
  CONFIRMADO: 'CONFIRMADO',
  CANCELADO: 'CANCELADO',
};

export const SUBMISSION_STATUS = {
  PENDIENTE: 'PENDIENTE',
  APROBADO: 'APROBADO',
  RECHAZADO: 'RECHAZADO',
};

export const CULTURE_CATEGORIES = [
  'FESTIVALES',
  'GASTRONOMIA',
  'TRADICIONES',
  'HISTORIA',
  'ARTE',
  'IDIOMA',
];

export const ACTIVITY_CATEGORIES = [
  'CULTURAL',
  'AVENTURA',
  'GASTRONOMIA',
  'NATURALEZA',
  'COMPRAS',
  'NOCTURNO',
  'HISTORICO',
];

export const SUBMISSION_TYPES = ['ACTIVIDAD', 'HOTEL', 'VUELO'];
